FROM arm32v7/debian:buster

# Update apt
RUN apt-get update

# Install Python 2.7 versions of pygame and pip
##RUN apt-get install -y python-pygame python-pip

# Install Python 3 versions of pygame and pip
RUN apt-get install -y python3-pygame python3-pip

# Install SDL 1.2
RUN apt-get install -y libsdl1.2debian
