version: "3.6"

volumes:
  sonos-pi-controller:

services:
  app:
    container_name: sonos-pi-controller
    privileged: true
    network_mode: host
    build: .
    env_file: .env
    volumes:
      - sonos-pi-controller:/usr/src/app
      - '/sys/class/backlight:/sys/class/backlight'
      - '/etc/pointercal:/etc/pointercal'
      - '/etc/ts.conf:/etc/ts.conf'
    devices:
      - "/dev/fb1:/dev/fb1"
      - "/dev/input/event0:/dev/input/event0"
